[build]
    command ="npm run build"
    publish = "dist"
    functions = "_lambda-build"

[build.environment]
    NODE_VERSION = "10.15"
    NPM_VERSION = "6.10.2"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# Netlify subdomain
[[redirects]]
    from = "https://apurvmishra.netlify.com/*"
    to = "https://apurvmishra.xyz/:splat"
    status = 301
    force = true


[[redirects]]
    from = "https://www.apurvmishra.xyz/*"
    to = "https://apurvmishra.xyz/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://apurvmishra.xyz"
    to = "https://apurvmishra.xyz/"
    status = 301
    force = true

# Bots
[[redirects]]
    from = "/wp-login.php"
    to = "https://www.google.com/"
    status = 302
    force = true

# Favicon
[[redirects]]
    from = "/assets/images/touch/*"
    to = "/assets/images/favicon/:splat"
    status = 301
    force = true

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
