[build]
    command = "yarn run build"
    publish = "dist"
	functions = "functions"
[build.environment]
    NODE_VERSION = "8.9.4"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"
[[redirects]]
  from = "/blog/livng-in-college-wynd-and-cowgate"
  to = "/blog/living-in-college-wynd-and-cowgate"

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404

# Favicon
[[redirects]]
    from = "/assets/images/touch/*"
    to = "/assets/images/favicon/:splat"
status = 301
